### ISSUE TITLE
Ionic 5 with Angular?

### ISSUE THREAD

**Issue by pickfire** [ionic-team/ionic-unit-testing-example#100]

**Comment by leifwells** [comment]
When you install Ionic 5 with Angular 9, testing should automagically set itself up for you.

**Comment by pickfire** [comment]
Yes, but how about testing with the ionic lifecycle hooks and inclusion of the ionic components and events? Based on what I am doing now, I am including them one by one since I don't need everything, I need to go through the source to do that like `IonSelect`.
