### ISSUE TITLE
Using the whole ionic theme in karma specs

### ISSUE THREAD

**Issue by mwager** [ionic-team/ionic-unit-testing-example#24]
Does anyone know a way to get the unit tests working with the whole ionic theme? I.e. rendering Angular/Ionic components in the karma view (in the browser, e.g. http://localhost:9876/debug.html) with **real ionic styling**?

Especially I mean integrating the following paths:

* node_modules/ionic-angular/themes
* node_modules/ionicons/dist/scss
* node_modules/ionic-angular/fonts
* and the variables.scss from an ionic app

By using the method `configureIonicTestingModule()` from the "clicker app" (see https://github.com/lathonez/clicker/blob/3a8b6103c86d827130a41a3406a7fbba8c776bab/src/test-utils.ts), we got it working that ionic tags are compiled in the karma output, but they have no styles.

Maybe someone already solved this, we are trying, but could not make it work yet.

Cheers & Thanks, 
Michael

**Comment by lathonez** [comment]
I looked into this a while ago, and the answer I arrived at was to use e2e testing for this.

When unit testing, none of the above modules / paths apply to the "black box" component you are testing. At most, you may apply some style or other dynamically depending on your component's logic, which you can test for by grabbing the `nativeElement` from the `fixture`.

Any more than that and I think you are in e2e land.

Very happy to be corrected ^^
