### ISSUE TITLE
e2e cannot select elements

### ISSUE THREAD

**Issue by stefanhuber** [ionic-team/ionic-unit-testing-example#28]
It's great that e2e support is provided! However I have problems to use it. The example you provide for selecting the title of the page works great. It only seems that it is not possible to select elements from the template/page which is loaded.

`
element(by.css('.title'))
            .getText()
            .then(text => {
                console.log("text from .title: ", text);
            });
`

The error is the following:
Failed: No element found using locator: By(css selector, .title)

So my conclusion is, that the element selection is started before the page has been loaded fully. Is there a way to wait until the page has fully loaded?

I have tried already things like, without success:
waitForAngular: http://www.protractortest.org/#/api?view=ProtractorBrowser.prototype.waitForAngular

**Comment by stefanhuber** [comment]
Ok.
I have found the cause of my problem. The main/root component needs to have a [rootPage](https://github.com/driftyco/ionic-unit-testing-example/blob/master/src/app/app.html#L18) otherwise at least for me this doesn't work...

**Comment by stefanhuber** [comment]
Unfortunately, this is a problem. As I have to initialize a database, before the first page can be shown. 

In my case the [rootPage](https://github.com/driftyco/ionic-unit-testing-example/blob/master/src/app/app.component.ts#L16) is set to `null` and only after the initialization i use the `Nav` element with `nav.setRoot(MainPage)` to serve the first page of my app.

**Comment by leifwells** [comment]
Are you trying to isolate the page to test it?

Have you tried navigating to the page you are testing via protractor code? i.e. start the app, use whatever navigation necessary to get the the page you are testing, start testing.

**Comment by stefanhuber** [comment]
Thank you for your reply! I have tried now many things, but cannot get it to work properly. As you suggested, I created a deeplink configuration:
https://github.com/getbitpocket/bitpocket-mobile-app/blob/master/src/app/app.module.ts#L111

In my e2e test I try to navigate to the respective url:
https://github.com/getbitpocket/bitpocket-mobile-app/blob/master/e2e/onboarding/onboarding.e2e-spec.ts#L9

However, the protractor api doesn't work as I expect it to work. At least I always get errors like this:

```
Failed: Timed out waiting for asynchronous Angular tasks to finish after 11 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular
      While waiting for element with locator - Locator: By(css selector, .button-large)
```

I also use `sendKeys` and one can see that for a second something is written inside the input field, however not visible anymore.

I am quite stuck here, and don't know what is wrong here. Does anybody have any suggestions? Thanks...

**Comment by leifwells** [comment]
I downloaded your repo to do some tests and was receiving the errors you reported.

I did a little Googling and found this issue: [https://github.com/angular/angular/issues/11853#issuecomment-268430829](https://github.com/angular/angular/issues/11853#issuecomment-268430829)

I added `browser.ignoreSynchronization = true;` as that code sample did and tests started working.

_**WARNING:** Although these tests are working, **I believe this is more of a hack than a fix.** There must be an issue with Angular waiting for something to happen. To make this problem go away, you first need to figure out what Angular is waiting on._

I honestly don't know how to further assist. At the very least, you can continue to create tests.

**Comment by stefanhuber** [comment]
Thanks for you help and time!

I found out a little bit more about the problem I am facing. Sending keys to `ion-input` seems to be a bit problematic. Protractor is sending keys before the component (ion-input) was fully initialized. Therefore after sending keys the ngModel value overrides the input value...

My solution:
```
let el = element(by.css('input[type="text"]'));
browser.sleep(500);
el.sendKeys(input);
```

After page loading and selection of ion-input element, waiting a little bit before sending keys. Maybe there are better solutions...

For now it works for me, so the issue can be closed.
