### ISSUE TITLE
e2e tests shows error

### ISSUE THREAD

**Issue by AresDev** [ionic-team/ionic-unit-testing-example#55]
I get an error executing e2e the following error:

 - Failed: Angular could not be found on the page http://localhost:8100/.If this is not an Angular application, you may need to turn off waiting for Angular.
                                  Please see
                                  https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
        - Failed: Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"

Can you tell me what I am doing wrong?

Thanks!

**Comment by leifwells** [comment]
To run your e2e tests, you have to be running the Ionic server, i.e. `ionic serve`, at the same time.

Just load up a new terminal window and run the command then run your e2e tests.

**Comment by AresDev** [comment]
Excellent, thank you!

**Comment by k7moorthi** [comment]
You can also refer to: https://github.com/lathonez/clicker/blob/master/protractor.conf.js#L26.

This will handle serving the Ionic app. So you can do your testing without any worries.

NOTE: Don't forget to install 'connect' and 'serve-static' packages from npm.
