### ISSUE TITLE
How to test async functions ?

### ISSUE THREAD

**Issue by jainAdijain** [ionic-team/ionic-unit-testing-example#60]
Hi, Please see the following link for the question. I posted on this because there is very less community support involved in ionic unit testing.Hope anyone here would surely help me out.

https://stackoverflow.com/questions/45311260/how-to-test-an-asynchronous-function-using-karma-jasmine-in-ionic2

Thanks

**Comment by nicobytes** [comment]
Hi! @jainAdijain for async functions in Angular there are utils as fakeAsync and tick, for example:

https://gist.github.com/nicobytes/1ada769aa8f4121a3d4a9dce634c52a5

The key is use fakeAsync and when call your async function call tick()
