### ISSUE TITLE
404 Warning for assets

### ISSUE THREAD

**Issue by 11lein** [ionic-team/ionic-unit-testing-example#64]
I've got 404 warnings for images, which could not load while testing. I don't want to test the images, just suppress the warnings. 

After some research something like this  
```
    files: [{
        pattern: './karma-test-shim.js',
        watched: true
      },
      {
        pattern: '../src/assets/img/*.png',
        watched: false, 
        included: false, 
        served: true
      }
    ],

    proxies: {
      '/assets/img/': '/base/src/assets/img/'
    },
```
in the karma.conf.js should help, but I've got still 

` WARN [web-server]: 404: /base/src/assets/img/ionic_logo.png `

I have fiddled around with the path expressions, but did't get it. 

If someone please could help, Here my example [https://github.com/11lein/ionic-unit-testing-example](https://github.com/11lein/ionic-unit-testing-example)

**Comment by leifwells** [comment]
I've tried many times to make those warnings go away and failed. If anyone has insights into how to better control these warnings I would love to hear about it.

**Comment by datencia** [comment]
Hi, seems related to relative paths. To solve it I've created a `karma.conf.js` file at the project root level that imports the config at the `test-config` folder, then I've changed some paths to point to the right files.

See the PR #66

**Comment by 11lein** [comment]
@datencia  thx for your help. Your fix, setting `baspath` to **the relative project root** and adjust the `karma-test-shim.js` path works pretty fine for me.

Issue solved.
