### ISSUE TITLE
Use ionic native mocks in tests

### ISSUE THREAD

**Issue by K1N5L4Y3R** [ionic-team/ionic-unit-testing-example#71]
**Note**: This is a duplicate from https://github.com/chrisgriffith/ionic-native-mocks/issues/7. I apologize in advance if this is not the place for this kind of questions

I am using unit and end to end tests on my app (with Karma, Jasmine and Protactor by following this repo and the [tutorial](https://leifwells.github.io/2017/08/27/testing-in-ionic-configure-existing-projects-for-testing/) you mention)

Let's say I have a class that calls the actual Ionic Native wrapper for a plugin, but I want to **test** this component. For tests, I'd like to use the **mock** for that Ionic Native wrapper, instead of the wrapper itself. I think I could use [ionic-native-mocks](https://github.com/chrisgriffith/ionic-native-mocks), which you mention in your readme. Please see the example below:

```
// My class using an Ionic Native wrapper
import { BLE } from '@ionic-native/ble';

export class ClassToBeTested {
  uuid: string
  ble: BLE

  constructor (uuid) {
    this.uuid = uuid
    this.ble = new BLE()
  }

  connect () {
    this.ble.connect(this.uuid)
    // ...
  }
}
```

```
// Test:
import { ClassToBeTested } from "../../lib/class_to_be_tested"

describe('ClassToBeTested', () => {
  it('can be instantiated', () => {
    let instance:ClassToBeTested = new ClassToBeTested("a")
    expect(instance instanceof ClassToBeTested).toBe(true)
    expect(instance.uuid).toBe("a")
  })

  it('can connect', () => {
    let instance:ClassToBeTested = new ClassToBeTested("a")
    expect(instance.connect).not.toThrow()
    // This fails: Expected function not to throw, but it threw TypeError: Cannot read property 'ble' of undefined.
  })
})
```

I think that what I need is to use `BLEMock` instead of `BLE` when testing. How can this be done?

**Comment by leifwells** [comment]
Have you read [this blog post](https://chrisgriffith.wordpress.com/2017/08/21/customizing-ionic-native-mocks/)?

**Comment by K1N5L4Y3R** [comment]
Thanks for the tip. That's actually kind of what I was doing. I ended up writing my own mock that used the Ionic Native mock, but I was using Jasmine's `spyOn()`, since my class is not an Angular component (yet), but once it is, this is probably the way to go.

Thanks again. Closing this and the original issues.
