### ISSUE TITLE
unable to execute test cases

### ISSUE THREAD

**Issue by pallaviMN** [ionic-team/ionic-unit-testing-example#74]
Hi team,
 I am getting below error when i tried in my project

PhantomJS 2.1.1 (Windows 8 0.0.0) Reverse unit test s toBeUndefined Should Controller exist FAILED
        D:/InsightApp3rdMarch/www/lib/angular/angular.js:4641:53
        forEach@D:/InsightApp3rdMarch/www/lib/angular/angular.js:321:24
        loadModules@D:/InsightApp3rdMarch/www/lib/angular/angular.js:4601:12
        createInjector@D:/InsightApp3rdMarch/www/lib/angular/angular.js:4523:30
        workFn@D:/InsightApp3rdMarch/www/lib/angular-mocks/angular-mocks.js:3074:60
        loaded@http://localhost:9876/context.js:162:17
PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0 secs / 0.018 secs)

**Comment by leifwells** [comment]
@pallaviMN 
This project doesn't use PhantomJS. For E2E testing, we use [Protractor](http://www.protractortest.org/#/).
