### ISSUE TITLE
Tests fail due to: "TypeError: Cannot read property 'run' of null"

### ISSUE THREAD

**Issue by spencer-whitman** [ionic-team/ionic-unit-testing-example#88]
I have added the sample test files to an existing ionic 3 project and replaced instances of "MyApp" with the class name of my actual app. When I run `npm test` both default tests fail with the below error repeated four times.

    TypeError: Cannot read property 'run' of null
        at <Jasmine>
        at UserContext.<anonymous> (http://localhost:9876/base/test-config/karma-test-shim.js:130803:34)
        at <Jasmine>
        at ZoneDelegate.invokeTask (http://localhost:9876/base/test-config/karma-test-shim.js:127920:31)
        at Zone.runTask (http://localhost:9876/base/test-config/karma-test-shim.js:127687:47)
        at drainMicroTaskQueue (http://localhost:9876/base/test-config/karma-test-shim.js:128097:35)

And if this helps, system info:

    $ ionic info
    
    cli packages: (/Users/swhitman/FIClock/node_modules)
    
        @ionic/cli-utils  : 1.19.2
        ionic (Ionic CLI) : 3.20.0
    
    global packages:
    
        cordova (Cordova CLI) : 6.5.0 
    
    local packages:
    
        @ionic/app-scripts : 3.0.0
        Cordova Platforms  : android 6.1.2 ios 4.3.1
        Ionic Framework    : ionic-angular 3.7.0
    
    System:
    
        ios-sim : 5.0.13 
        Node    : v8.1.3
        npm     : 4.6.1 
        OS      : macOS Sierra
        Xcode   : Xcode 9.2 Build version 9C40b 
    
    Environment Variables:
    
        ANDROID_HOME : not set
    
    Misc:
    
        backend : legacy

**Comment by alexmbrown** [comment]
I'm also receiving the same error.

**Comment by VolodymyrAndrushchak** [comment]
@spencer-whitman  @alexmbrown 

I had the same problem but updating `zone.js` to the latest version was helped me.

**Comment by spencer-whitman** [comment]
Thanks for the suggestion @VolodymyrAndrushchak - I do not have zone.js installed at all however. Is this a dependency?

**Comment by alexmbrown** [comment]
I can confirm that upgrading zone.js from 0.8.18 to 0.8.26 does resolve this issue. @spencer-whitman zone.js is a required dependency of angular 2+ and is imported by `karma-test-shim.js`

**Comment by spencer-whitman** [comment]
Thanks @alexmbrown - npm list zone returned nothing, so I thought it was broken. I can also confirm that updating zone.js to 0.8.26 in package.js fixes this issue, thanks!
